
    <section class="top">
        <div class="con flex">
            <ul>
                <li>Career</li>
                <li>Services</li>
                <li>Interest Rates</li>    
            </ul>
            <ul>
                <li><i class="bi bi-search"></i></li>
                <li><i class="bi bi-person-fill"></i></li>
            </ul>
        </div>

    </section>

    <section class="header">
       <div class="con flex">
        <img class="logo" src="image/logo.png" alt="Logo">
        <div>
            <img src="image/youtube.png" alt="" class="qr">
            <img src="image/fb.png" alt="" class="qr">
        </div>
       
       </div>
    </section>
    <nav>
        <div class="con flex">
            <ul>
                <li><a href="">HOME</a></li>
                <li><a href="#">ABOUT US<i class="bi bi-chevron-down icon"></i></a>
                    <ul class="dropdown">
                        <li><a href="about.html">About SKBBL</a></li>
                        <li class="subli"><a href="">Organizational Structure<i class="bi bi-chevron-right icon"></i></a>
                            <ul class="dropdown2">
                                <li><a href="">Ownership Structure</a></li>
                                <li><a href="">Organogram</a></li>
                            </ul>
                        </li>
                        <li><a href="">Progress at a Glance</a></li>
                        <li><a href="">Outreach Of SKBBL</a></li>
                        <li><a href="">CEO's Message</a></li>
                        <li class="subli"><a href="">Team<i class="bi bi-chevron-right icon"></i></a>
                            <ul class="dropdown2">
                                <li><a href="">Board Of Directors</a></li>
                                <li><a href="">Management Team</a></li>
                            </ul>
                        </li>
                        <li><a href="">Support and Collaborations</a></li>
                        <li><a href="">CSR and CPF Activities</a></li>
                        <li class="subli"><a href="">Small Farmer Summits<i class="bi bi-chevron-right icon"></i></a>
                            <ul class="dropdown2">
                                <li><a href="">Small Farmers Summit 2019</a></li>
                                <li><a href="">Small Farmers Summit 2014</a></li>
                            </ul>
                        </li>
                        <li><a href="">About Partner Co-operatives</a></li>
                    </ul>
                </li>
                <li><a href="">PRODUCT & SERVICES<i class="bi bi-chevron-down icon"></i></a>
                    <ul class="dropdown">
                        <li  class="subli"><a href="">Loan<i class="bi bi-chevron-right icon"></i></a>
                            <ul class="dropdown2">
                                <li><a href="">Microfinance Wholesale Credit</a></li>
                                <li><a href="">Credit For Meat & Milk Production</a></li>
                                <li><a href="">Renewable Energy Loan</a></li>
                                <li><a href="">Livelyhood Loan</a></li>
                                <li><a href="">Working Capital Loan For Cooperative Tea Industry</a></li>
                                <li><a href="">View All</a></li>
                            </ul>
                        </li>
                        <li class="subli"><a href="">Services<i class="bi bi-chevron-right icon"></i></a>
                            <ul class="dropdown2">
                                <li><a href="">Farmers to Farmers Replication Programme</a></li>
                                <li><a href="">Business Expansion Programme</a></li>
                                <li><a href="">Livestock Insurance Program</a></li>
                                <li><a href="">View All</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li><a href="">REPORTS<i class="bi bi-chevron-down icon"></i></a>
                    <ul class="dropdown">
                        <li><a href="">Annual Report</a></li>
                        <li><a href="">Quarterly Report</a></li>
                        <li><a href="">AGM Minute Report</a></li>
                        <li><a href="">Right to Information</a></li>
                    </ul>
                
                </li>
                
                <li><a href="">PUBLICATIONS<i class="bi bi-chevron-down icon"></i></a>
                    <ul class="dropdown">
                        <li><a href="">Notice</a></li>
                        <li><a href="">Career</a></li>
                        <li><a href="">Newsletter</a></li>
                        <li><a href="">Downloads</a></li>
                        <li><a href="">Other Publications</a></li>

                    </ul>
                </li>
                <li><a href="">EVENTS & VIDEOS<i class="bi bi-chevron-down icon"></i></a>
                    <ul class="dropdown">
                        <li><a href="">Photo Gallery</a></li>
                        <li><a href="">Videos</a></li>
                        <li><a href="">News/Events</a></li>
                        <li><a href="">Success Stories/Blogs</a></li>
                    </ul>
                </li>
                <li><a href="">PROJECTS</a></li>
                <li class="mail"><a href="">WEBMAIL</a></li>
            </ul>
        </div>
    </nav>
